version: '3'

services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.envs/.postgres
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - conexfutpro


volumes:
  pgdata:

networks:
  conexfutpro:
