version: '3'

services:

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 futpro.wsgi:application
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - conexfutpro


volumes:
  pgdata:

networks:
  conexfutpro:
