# Generated by Django 5.0.6 on 2024-06-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventausuario',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
