# Generated by Django 5.0.6 on 2024-06-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='futcoins',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
