# Generated by Django 5.0.6 on 2024-06-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_lotefutcoins_comprafutcoins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprafutcoins',
            name='cvv',
            field=models.CharField(max_length=256),
        ),
    ]
