# Generated by Django 5.0.6 on 2024-05-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='jugadores/'),
        ),
    ]
