# Generated by Django 5.0.6 on 2024-06-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
